### ISSUE TITLE
trongate-datetime.js

### ISSUE THREAD

**Issue by lgg1980** [trongate/trongate-framework#104]
Hi there. Hope everyone having a nice time in the Trongate Family.

I'm from Spain (I apologize in advance if my English it's currently a bit atrocious to say the least, for that I'm sorry)

My date format it's DD/MM/YYYY . 

For example I do a new module let's name it People with a Name, another field for Surname and Birth Date. 

Then I do change Trongate's validation helper on Birth Date to 'required|valid_datepicker_eu' in my case.

Looking thru trongate-datetime.js I'd only need to change var localeString (which it's on line 3) to 'es-ES'. Well, not exactly.

In line 97 there's what I believe it's the formatted output which needs to be changed as well to 'es-ES' for my date format to work.

Hope this helps and if I'm wrong in any way please kindly push me in the right direction.

Thanks everyone.

**Comment by ReDeLe-design** [comment]
Have made a pull-request for trongate-datetime.js.
you can use it in the meantime.

**Comment by lgg1980** [comment]
many thanks!

**Comment by ReDeLe-design** [comment]
The pull-request is merged. I suggest to close this issue.
