### ISSUE TITLE
Download link 

### ISSUE THREAD

**Issue by normtomlins** [trongate/trongate-framework#117]
The download link for Mac doesn't work on the website - https://trongate.io/download

It returns https://github.com/trongate/trongate-framework/.dmg

I am using a Mac M1

**Comment by DaFa66** [comment]
Looks like all links to download the Desktop app are down, I'm sure DC will have this up very soon.

**Comment by trongate** [comment]
Thanks for that.  We're now fixed.  Many thanks to DaFa for helping out with that one.
