### ISSUE TITLE
I can't register as a member of trongate.io

### ISSUE THREAD

**Issue by wfsdaj** [trongate/trongate-framework#127]
I can't register as a member of trongate.
I use email addresses such as gmail, sina, 126, and qq, but I can't receive the activation website.

**Comment by mi-ke-dev** [comment]
> I can't register as a member of trongate. I use email addresses such as gmail, sina, 126, and qq, but I can't receive the activation website.

Do you have a VPN? Enable it, choose a random location, and try again.

Sometimes my network (usually if I'm visiting a client/firewall) will have weird rules about which site's SSL should be trusted. Just a thought.

**Comment by trongate** [comment]
I've had two reports from people with this challenge.  Both of whom are using Hotmail.  I'm currently investigating this one and I apologise for your troubles.  I'll check in shortly.

**Comment by freedms2021** [comment]
I may be one of the hotmail.com users you referenced.  I just registered again with a gmail account and worked flawlessly.

**Comment by trongate** [comment]
Hi,

That's excellent.  Thanks for letting me know.

Cheers!

DC

**Comment by Andrewsuares** [comment]
I've had maximum problems with Outlook(hotmail) and Yahoo. They reject emails sent by reputed services such as AWS and then AWS says your SPAM rate is high. Outlook and Yahoo are the worst in dealing with SPAM. I've sent out newsletters that the user subscribed for and Yahoo says its SPAM.

**Comment by freedms2021** [comment]
Thanks Andrew.  Just to clarify.  The account creation / verification email came through, but the link took me to a expired / url invalid page when clicked.  I also tried a pwd reset link (although my account had not yet been verified for reasons stated above, so I didn't expect that link to work either) that took me to the same page / message.  If someone would like to verify the link(s) I received in outlook against the db, please let me know.  I'll give it a shot with my yahoo email in a bit to see how that goes.

**Comment by trongate** [comment]
It's one of these things that would probably be a two minute fix, if only I could repeat the problem.  But I can't.  :(

Anyway... just to give you an update on this... I'm currently building a social media authenticator.  So, hopefully people will be able to come on board without any miserable sign up process.  

If anybody out there is able to repeat a fault and is happy to share screens and meet on Skype then I'd be very happy to do that.

Cheers!

**Comment by Andrewsuares** [comment]
Is it possible that Outlook is adding something to the link that would send a wrong GET request to enable the account? Maybe DC has a sanitizer check in the GET that would reject the modified URL?

**Comment by trongate** [comment]
I have added a social auth feature to the site.  Hopefully that'll help.
