### ISSUE TITLE
$this->upload_file() no longer works for non image files

### ISSUE THREAD

**Issue by ReDeLe-design** [trongate/trongate-framework#128]
because inside trongate.php function img_helper->upload($data) is called instead of file_helper->upload($data)

`
public function upload_file($data) {
        $this->img_helper->upload($data); 
    }
`

and also inside ignition.php the load of file_helper is missing!

`
$tg_helpers = ['form_helper', 'flashdata_helper', 'img_helper', 'url_helper', 'validation_helper'];
define('TRONGATE_HELPERS', $tg_helpers);
`
and later on
`
foreach (TRONGATE_HELPERS as $tg_helper) {
    require_once 'tg_helpers/'.$tg_helper.'.php';
}
`

There is a pull request for this.

**Comment by trongate** [comment]
Many thanks for this and I apologise for the sloppy response.  I'll be coming right onto this soon and there will also be some Learning Zone training coming up covering this.  I apologise if I have not yet responded to your pull request(s).  Rest assured, it's all coming up.  Ahoy!!!!!!!

**Comment by trongate** [comment]
This has now been fixed with v1.3.3040.  For full details about how file uploading works with Trongate, please refer to https://trongate.io/docs/information/a-general-overview-of-file-uploading

Thank you for raising this issue.
