### ISSUE TITLE
TYPEERROR: CONN.QUERY IS NOT A FUNCTION

### ISSUE THREAD

**Issue by Ei2g** [trongate/trongate-framework#131]
Hi,
I appreciate there have been a couple of issues raised for this error.  However I have just experienced it and the resolution for me was not as per the others.

My set-up is that I am using a remote Windows development stack with Trongate Desktop on Windows 10 locally and remotely running PHP 8.0 / MySQL 8.0 (also running IIS 8.5 - I will have no truck with your non-Mayan calendars :-)  )

The issue for me was that mySQL user accounts where using "Caching sha2 authentication" for password hashing, changing this to "Native MySQL Authentication" enabled Trongate Desktop to remotely create the required DB.

Hope this helps.

**Comment by trongate** [comment]
Hi.  Thanks so much for this.  I'd be super grateful if you could post your comment in the Help Bar.  It'll definitely be helpful for somebody out there.  Cheers!  - DC
