### ISSUE TITLE
missing method remove_special_characters in class Validation_helper

### ISSUE THREAD

**Issue by jchouix** [trongate/trongate-framework#137]
Hi,
the method  **remove_special_characters** does not exist in the class **Validation_helper** in the file **engine/tg_helpers/validation_helper.php** at **line 420**
Best regards.

**Comment by trongate** [comment]
Thank you.  That's awesome.  I will look into this shortly.  I appreciate your pull request too.  Great stuff.  Just waiting for a moment when I have a little time to tune into this.  Many thanks.  I'll be in touch shortly. - DC

**Comment by trongate** [comment]
Okay.  I've had a look at it.  The obvious solution appears to be adding a remove_special_characters function.  However, as suggested in a previous message, I think the whole idea of having unique() is deeply flawed.  There is no remove_special_characters function I'm aware of that can be applied universally.  In other words, the moment Trongate gets adopted by developers who build sites that use non-English languages, our unique function will be more of a hinderance than a help.  I think this is a big old bag of problems and the real solution is to _ditch_ unique.

Do you agree?

**Comment by jchouix** [comment]
Yes.

**Comment by trongate** [comment]
Okay, I have now removed 'unique'.  Thanks for raising this.
