### ISSUE TITLE
Deprecated message on API Manager

### ISSUE THREAD

**Issue by gstesq** [trongate/trongate-framework#140]
Getting:

<br />
<b>Deprecated</b>:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in <b>/Applications/MAMP/htdocs/my_business/engine/Standard_endpoints.php</b> on line <b>903</b><br />
[]

![image](https://user-images.githubusercontent.com/15643243/229528584-e3827aec-1715-464e-8c22-0be4a8b03567.png)

Any ideas?

**Comment by trongate** [comment]
I'm about to live stream so that I can deal with these things in real
time.  Come on down!

**Comment by trongate** [comment]
Hi!  I've added settype($query_str, 'string');  Hopefully that should fix it.  It's a bit of a drag coding blind but fingers crossed - we should be good.

**Comment by gstesq** [comment]
Sorry my mistake - I actually added my own if else fix and forgot about it. The records in the DB have no effect, as you no doubt noticed.

Same message was showing with a record in DB just shows the records at the end.

I'll test the new code and update.

**Comment by trongate** [comment]
That's okay.  Take your time.
