### ISSUE TITLE
date-range picker doesn't show calendar

### ISSUE THREAD

**Issue by neoxnitro** [trongate/trongate-framework#150]
No calendar is displayed when I used the "date-range" ... does I use it properly ? or it is a bug ? or a not finished feature ?

```php

	$attr_date["class"] = "date-range";
	echo form_input("test", "05/07/2023", $attr_date);

```

**Comment by trongate** [comment]
Thanks.  I'll look into this!

**Comment by trongate** [comment]
I have completely rewritten all of the code related to date and time pickers.  Even though this work is not yet finished, your issue should now be resolved.  Thank you for bringing this to my attention.  If there's anything else that's not right, let me know.
