### ISSUE TITLE
Charset in db-connection

### ISSUE THREAD

**Issue by danielldl** [trongate/trongate-framework#154]
Hi,

I'm pretty new to Trongate and PHP so there might be a better way to do this...

I live in Sweden and we three special characters (Å Ä Ö). When connecting to MySQL-database they are shown incorrect. I added a "charset" setting the connect string in Model.php (line 33) and it works for me. Maybe there is a better to make do it. As a setting in the config- or database (config) file? 

Thanks,

Daniel

**Comment by trongate** [comment]
Given the fact that database connection details generally get set once and then left alone, I would recommend refraining from using problematic characters for your database credentials.
