### ISSUE TITLE
form_helper.php form_hidden() - Additional Code not working

### ISSUE THREAD

**Issue by redjaffa** [trongate/trongate-framework#171]
Hi DC,
Codefire here.

$additional_code is being passed to the form_hidden() "attributes" param instead of the "additional code" param.

function form_hidden($name, $value = null, $additional_code = null) {
    $html = form_input($name, $value, $additional_code);
    $html = str_replace(' type="text" ', ' type="hidden" ', $html);
    return $html;
}

Should be as below:

function form_hidden($name, $value = null, $additional_code = null) {
    $html = form_input($name, $value, **NULL**, $additional_code);
    $html = str_replace(' type="text" ', ' type="hidden" ', $html);
    return $html;
}

Cheers

**Comment by trongate** [comment]
Thank you.  You're right.  Nicely spotted!

Your solution is good.  Could you please copy the code below and replace the form_hidden() function, then submit a pull request?  I'd like you to be given the credit for this.

/**
 * Generate an HTML hidden input field.
 *
 * @param string $name The name attribute for the hidden input field.
 * @param string|null $value The initial value of the hidden input field. If not provided, it will be empty.
 * @param string|null $additional_code Additional HTML code to append to the hidden input field.
 * @return string The generated HTML hidden input field.
 */
function form_hidden($name, $value = null, $additional_code = null) {
    $html = form_input($name, $value, null, $additional_code); // Pass NULL as the third argument
    $html = str_replace(' type="text" ', ' type="hidden" ', $html);
    return $html;
}

**Comment by trongate** [comment]
I hope we're good.  If not, please reopen.
