### ISSUE TITLE
Inconsistent URL pattern in Trongate.io website.

### ISSUE THREAD

**Issue by iamprogrammerlk** [trongate/trongate-framework#185]
In the Tronegate.io website most of the time, a hyphen is used to separate the word in links. but, in some places, I found the underscore as a word separator.

Why does this inconsistency exist?

https://trongate.io/help_bar
https://trongate.io/social_auth/login
https://trongate.io/terms_of_service
https://trongate.io/privacy_policy

**Comment by trongate** [comment]
All refused.  Please stop trying to help me.
