### ISSUE TITLE
Trongate app does not include trongate-mx.js when updating

### ISSUE THREAD

**Issue by imoldovavan** [trongate/trongate-framework#193]
When updating an existing app using the Trongate app the trongate-mx.js is not included in the update.

**Comment by trongate** [comment]
Yes, it's true.   The automatic updates online update whatever is inside the directory named 'engine'.  I do not plan on updating trongate-pages.mx frequently.   Soon it will be in a settled state and there will be no need to update it via the desktop app.  For the moment, you'll gonna have to do manual updates by grabbing it from GitHub.
