### ISSUE TITLE
Trouble with Trongate Login

### ISSUE THREAD

**Issue by brendanknights** [trongate/trongate-framework#197]
Login doesn't seem to be working on latest Trongate new project generation and also on the Trongate website.

Maybe I missed something in the last little while - but I started a new local project using the Windows app and XAMPP, but when I attempted to login to the admin/admin area, it didn't work.

So - I thought, I'll go to the Help bar to ask there... nothing obvious in the recent posts. Maybe I should login and open my own question - can't login there either.

I thought, might be my own network or DNS blocking something? No - used a fresh browser on 2 different networks, same problem. Just goes to a white screen at the endpoint: https://trongate.io/members/submit_login

Is this localised to me? A recent update? A change to how things work now? What did I miss?

**Comment by brendanknights** [comment]
Github login seems to work okay - maybe just an issue with user/pass logins right now?

**Comment by trongate** [comment]
I think we're good now.  Can you confirm?

**Comment by brendanknights** [comment]
> I think we're good now. Can you confirm?

I created a test user and I can confirm that user/password logins work now at trongate.io
My original account email address had a + in the email address and this one isn't working - no matter, I'll keep my test user ;)

Confirming as well that a new trongate app generated 5 minutes ago now logs in with admin/admin ;)

Love your work DC - cheers, BK
